_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 41
                - 105
            "2":
                - 1
                - 41
                - 105
            "3":
                - 2
                - 16
                - 17
                - 55
            "4": 3.11.11
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
GSP_input_length:
    value: 4800
batch_size:
    value: 60
embed_dim:
    value: 512
learning_rate:
    value: 0.01
spatial_coord_dim:
    value: 2
spatial_sinusoidal_dim:
    value: 2
